[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_transfer = "2GP1714MWmjJRnv49DyQnjRKwfCVFANmetaEHaprJE1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aphomer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

